USE [master]
GO

/****** Object:  Database [ETrade1]    Script Date: 28.08.2022 02:43:25 ******/
CREATE DATABASE [ETrade1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ETrade1', FILENAME = N'C:\Users\canof\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\ETrade1.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ETrade1_log', FILENAME = N'C:\Users\canof\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\ETrade1.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [ETrade1] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ETrade1].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ETrade1] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [ETrade1] SET ANSI_NULLS ON 
GO

ALTER DATABASE [ETrade1] SET ANSI_PADDING ON 
GO

ALTER DATABASE [ETrade1] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [ETrade1] SET ARITHABORT ON 
GO

ALTER DATABASE [ETrade1] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ETrade1] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ETrade1] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ETrade1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ETrade1] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [ETrade1] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [ETrade1] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ETrade1] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [ETrade1] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ETrade1] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ETrade1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ETrade1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ETrade1] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ETrade1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ETrade1] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ETrade1] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ETrade1] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ETrade1] SET RECOVERY FULL 
GO

ALTER DATABASE [ETrade1] SET  MULTI_USER 
GO

ALTER DATABASE [ETrade1] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ETrade1] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ETrade1] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ETrade1] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ETrade1] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ETrade1] SET QUERY_STORE = OFF
GO

USE [ETrade1]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [ETrade1] SET  READ_WRITE 
GO


